name: local-tests

on: [ push ]

jobs:
  local-tests:
    name: Unit tests
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
      - uses: cachix/cachix-action@v13
        with:
          name: poetry2nix
          signingKey: "VhaWuN3IyJVpWg+aZvTocVB+W8ziZKKRGLKR53Pkld3YRZxYOUfXZf0fvqF+LkqVW0eA60trVd5vsqNONpX9Hw=="
      - run: |
          cp .env.test .env
      - run: |
          nix develop --command bash -c 'poetry install'
      - run: |
          nix develop --command bash -c 'poetry run pytest ./__tests__/local/ --cov app/ --cov-branch --cov-report=term --cov-fail-under=80'