name: unit-tests

on: [push]

jobs:
  tests:
    name: Unit tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
      - run: |
          cp .env.test .env
      - run: |
          nix develop --command \
            poetry install \
            poetry run pytest __tests__/*/*.py